# Generated by Django 5.1.6 on 2025-03-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.TextField(),
        ),
    ]
